apiVersion: v1
kind: Namespace
metadata:
  name: insightlearn-ai
  labels:
    name: insightlearn-ai
    project: insightlearn-cloud
    component: ai-services
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-resource-quota
  namespace: insightlearn-ai
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "5"
    requests.storage: "50Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: ai-limit-range
  namespace: insightlearn-ai
spec:
  limits:
  - default:
      cpu: 1000m
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    type: Container