apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightlearn-api
  namespace: insightlearn
  labels:
    app: insightlearn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insightlearn-api
  template:
    metadata:
      labels:
        app: insightlearn-api
    spec:
      containers:
      - name: api
        image: insightlearn-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ConnectionStrings__DefaultConnection
          value: "Server=postgresql.insightlearn-data.svc.cluster.local,5432;Database=InsightLearnDb;User Id=insightlearn;Password=InsightLearn2024!;TrustServerCertificate=true;"
        - name: ConnectionStrings__MongoDb
          value: "mongodb://insightlearn:InsightLearn2024!@mongodb.insightlearn-data.svc.cluster.local:27017/InsightLearnDb?authSource=admin"
        - name: ConnectionStrings__Redis
          value: "redis.insightlearn-data.svc.cluster.local:6379"
        - name: ConnectionStrings__Elasticsearch
          value: "http://elasticsearch.insightlearn-data.svc.cluster.local:9200"
        - name: AI__OllamaApiUrl
          value: "http://ollama-service.insightlearn-ai.svc.cluster.local:11434"
        - name: AI__DefaultModel
          value: "llama2"
        - name: Logging__LogLevel__Default
          value: "Information"
        - name: Logging__LogLevel__Microsoft.AspNetCore
          value: "Warning"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
# Disabled health checks for development
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 80
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 3
        volumeMounts:
        - name: temp-volume
          mountPath: /tmp
      volumes:
      - name: temp-volume
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - insightlearn-api
              topologyKey: kubernetes.io/hostname
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: insightlearn-api-hpa
  namespace: insightlearn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insightlearn-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60