apiVersion: apps/v1
kind: Deployment
metadata:
  name: insightlearn-web
  namespace: insightlearn
  labels:
    app: insightlearn-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insightlearn-web
  template:
    metadata:
      labels:
        app: insightlearn-web
    spec:
      containers:
      - name: web
        image: insightlearn-web:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ApiSettings__BaseUrl
          value: "http://insightlearn-api-service.insightlearn.svc.cluster.local"
        - name: ApiSettings__Timeout
          value: "30"
        - name: Authentication__Google__ClientId
          value: "your-google-client-id.apps.googleusercontent.com"
        - name: Authentication__Google__ClientSecret
          value: "your-google-client-secret"
        - name: Authentication__JWT__SecretKey
          value: "your-super-secret-jwt-key-that-is-at-least-32-characters-long"
        - name: Authentication__JWT__Issuer
          value: "InsightLearn.Cloud"
        - name: Authentication__JWT__Audience
          value: "InsightLearn.Users"
        - name: Authentication__JWT__ExpirationMinutes
          value: "60"
        - name: ConnectionStrings__Redis
          value: "redis.insightlearn-data.svc.cluster.local:6379"
        - name: Logging__LogLevel__Default
          value: "Information"
        - name: Logging__LogLevel__Microsoft.AspNetCore
          value: "Warning"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
# Disabled health checks for development
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 80
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        #   failureThreshold: 3
        # readinessProbe:
        #   httpGet:
        #     path: /health/ready
        #     port: 80
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   timeoutSeconds: 3
        #   failureThreshold: 3
        volumeMounts:
        - name: temp-volume
          mountPath: /tmp
        - name: static-files
          mountPath: /app/wwwroot
      volumes:
      - name: temp-volume
        emptyDir: {}
      - name: static-files
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - insightlearn-web
              topologyKey: kubernetes.io/hostname
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: insightlearn-web-hpa
  namespace: insightlearn
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: insightlearn-web
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60