apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-https-config
  namespace: insightlearn
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      upstream frontend {
        server insightlearn-frontend-service:80;
      }
      upstream backend {
        server insightlearn-backend-service:5000;
      }
      server {
        listen 0.0.0.0:443 ssl;
        server_name _;

        ssl_certificate /etc/ssl/certs/tls.crt;
        ssl_certificate_key /etc/ssl/private/tls.key;

        location / {
          proxy_pass http://frontend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https-proxy
  namespace: insightlearn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https-proxy
  template:
    metadata:
      labels:
        app: nginx-https-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tls-certs
          mountPath: /etc/ssl/certs/tls.crt
          subPath: tls.crt
        - name: tls-certs
          mountPath: /etc/ssl/private/tls.key
          subPath: tls.key
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-https-config
      - name: tls-certs
        secret:
          secretName: insightlearn-tls-secret
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-https-proxy-service
  namespace: insightlearn
spec:
  type: NodePort
  selector:
    app: nginx-https-proxy
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
