apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: insightlearn-data
  labels:
    app: mongodb
    tier: database
spec:
  serviceName: mongodb-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: database
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
    spec:
      containers:
      - name: mongodb
        image: mongo:7
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "insightlearn"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "InsightLearn2024!"
        - name: MONGO_INITDB_DATABASE
          value: "insightlearn"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: insightlearn-data
  labels:
    app: mongodb
    tier: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    app: mongodb
    tier: database
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: insightlearn-data
  labels:
    app: mongodb
    tier: database
spec:
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
  selector:
    app: mongodb
    tier: database
  clusterIP: None