apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: insightlearn-data
  labels:
    app: postgresql
    tier: database
spec:
  serviceName: postgresql-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      tier: database
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_DB
          value: "insightlearn"
        - name: POSTGRES_USER
          value: "insightlearn"
        - name: POSTGRES_PASSWORD
          value: "InsightLearn2024!"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - insightlearn
            - -d
            - insightlearn
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - insightlearn
            - -d
            - insightlearn
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: postgresql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: insightlearn-data
  labels:
    app: postgresql
    tier: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    app: postgresql
    tier: database
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-headless
  namespace: insightlearn-data
  labels:
    app: postgresql
    tier: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    app: postgresql
    tier: database
  clusterIP: None