apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: insightlearn-monitoring
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alertmanager@insightlearn.cloud'
      smtp_auth_username: 'alerts@insightlearn.cloud'
      smtp_auth_password: 'your-email-password'

    templates:
    - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 5s
        group_interval: 5s
        repeat_interval: 5m
      - match:
          severity: warning
        receiver: 'warning-alerts'
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h
      - match:
          service: database
        receiver: 'database-alerts'
        group_wait: 5s
        repeat_interval: 5m
      - match:
          service: api
        receiver: 'api-alerts'
        group_wait: 5s
        repeat_interval: 15m

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'cluster', 'service']

    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://webhook-receiver.insightlearn-monitoring.svc.cluster.local:9093/webhook'
        send_resolved: true

    - name: 'critical-alerts'
      email_configs:
      - to: 'admin@insightlearn.cloud'
        subject: '[CRITICAL] InsightLearn Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Details: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
        headers:
          Subject: '[CRITICAL] InsightLearn Alert'
      webhook_configs:
      - url: 'http://webhook-receiver.insightlearn-monitoring.svc.cluster.local:9093/webhook'
        send_resolved: true

    - name: 'warning-alerts'
      email_configs:
      - to: 'monitoring@insightlearn.cloud'
        subject: '[WARNING] InsightLearn Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Details: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

    - name: 'database-alerts'
      email_configs:
      - to: 'dba@insightlearn.cloud'
        subject: '[DATABASE] InsightLearn Database Alert: {{ .GroupLabels.alertname }}'
        body: |
          Database Alert Triggered:
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Database: {{ .Labels.job }}
          {{ end }}

    - name: 'api-alerts'
      email_configs:
      - to: 'api-team@insightlearn.cloud'
        subject: '[API] InsightLearn API Alert: {{ .GroupLabels.alertname }}'
        body: |
          API Alert Triggered:
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.kubernetes_service_name }}
          {{ end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: insightlearn-monitoring
  labels:
    app: alertmanager
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
        component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9093"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: monitoring-sa
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        fsGroup: 65534
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.26.0
        ports:
        - containerPort: 9093
          name: web
        args:
          - '--config.file=/etc/alertmanager/alertmanager.yml'
          - '--storage.path=/alertmanager'
          - '--web.route-prefix=/'
          - '--web.external-url=http://alertmanager.insightlearn-monitoring.svc.cluster.local:9093'
          - '--cluster.listen-address=0.0.0.0:9094'
          - '--log.level=info'
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager/
        - name: alertmanager-storage
          mountPath: /alertmanager
        resources:
          requests:
            memory: '128Mi'
            cpu: '100m'
          limits:
            memory: '256Mi'
            cpu: '200m'
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9093
          initialDelaySeconds: 30
          timeoutSeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9093
          initialDelaySeconds: 10
          timeoutSeconds: 30
          periodSeconds: 5
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
      - name: alertmanager-storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: insightlearn-monitoring
  labels:
    app: alertmanager
    component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
spec:
  ports:
  - name: web
    port: 9093
    targetPort: 9093
    protocol: TCP
  - name: cluster
    port: 9094
    targetPort: 9094
    protocol: TCP
  selector:
    app: alertmanager
  type: ClusterIP