apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insightlearn-api-monitor
  namespace: insightlearn-monitoring
  labels:
    app: insightlearn-api
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn
  selector:
    matchLabels:
      app: insightlearn-api
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: insightlearn-web-monitor
  namespace: insightlearn-monitoring
  labels:
    app: insightlearn-web
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn
  selector:
    matchLabels:
      app: insightlearn-web
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql-monitor
  namespace: insightlearn-monitoring
  labels:
    app: postgresql
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn-data
  selector:
    matchLabels:
      app: postgresql
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-monitor
  namespace: insightlearn-monitoring
  labels:
    app: mongodb
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn-data
  selector:
    matchLabels:
      app: mongodb
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-monitor
  namespace: insightlearn-monitoring
  labels:
    app: redis
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn-data
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: elasticsearch-monitor
  namespace: insightlearn-monitoring
  labels:
    app: elasticsearch
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn-data
  selector:
    matchLabels:
      app: elasticsearch
  endpoints:
  - port: http
    path: /_prometheus/metrics
    interval: 30s
    scrapeTimeout: 10s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ollama-monitor
  namespace: insightlearn-monitoring
  labels:
    app: ollama
    component: monitoring
spec:
  namespaceSelector:
    matchNames:
    - insightlearn-ai
  selector:
    matchLabels:
      app: ollama
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s

---
# Prometheus Operator CRDs (if not already installed)
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servicemonitors.monitoring.coreos.com
spec:
  group: monitoring.coreos.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              selector:
                type: object
              namespaceSelector:
                type: object
              endpoints:
                type: array
                items:
                  type: object
          status:
            type: object
  scope: Namespaced
  names:
    plural: servicemonitors
    singular: servicemonitor
    kind: ServiceMonitor

---
# Node Exporter for system metrics
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: insightlearn-monitoring
  labels:
    app: node-exporter
    component: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        component: monitoring
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: monitoring-sa
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
      - name: node-exporter
        image: prom/node-exporter:v1.6.1
        args:
        - '--path.procfs=/host/proc'
        - '--path.sysfs=/host/sys'
        - '--path.rootfs=/host/root'
        - '--collector.filesystem.ignored-mount-points'
        - '^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)'
        - '--collector.netclass.ignored-devices'
        - '^(veth.*|[a-f0-9]{15})$'
        - '--collector.netdev.device-exclude'
        - '^(veth.*|[a-f0-9]{15})$'
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
        resources:
          limits:
            memory: 180Mi
            cpu: 100m
          requests:
            memory: 90Mi
            cpu: 50m
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: root
          mountPath: /host/root
          mountPropagation: HostToContainer
          readOnly: true
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys
      - name: root
        hostPath:
          path: /

---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: insightlearn-monitoring
  labels:
    app: node-exporter
    component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9100"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
    protocol: TCP
  selector:
    app: node-exporter

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter-monitor
  namespace: insightlearn-monitoring
  labels:
    app: node-exporter
    component: monitoring
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s