apiVersion: v1
kind: Service
metadata:
  name: insightlearn-web-service
  namespace: insightlearn
  labels:
    app: insightlearn-web
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: insightlearn-web
---
apiVersion: v1
kind: Service
metadata:
  name: insightlearn-web-headless
  namespace: insightlearn
  labels:
    app: insightlearn-web
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: insightlearn-web